apiVersion: apps/v1
kind: Deployment
metadata:
  name: webssh-deployment
  labels:
    app: webssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webssh
  template:
    metadata:
      labels:
        app: webssh
    spec:
      containers:
      - name: webssh
        image: nfs.k8s:8080/k8s/webssh:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: harbor-secret
