apiVersion: apps/v1
kind: Deployment
metadata:
  name: webssh-deployment
  labels:
    app: webssh
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: webssh
  template:
    metadata:
      labels:
        app: webssh
    spec:
      containers:
      - name: webssh
        image: nfs.k8s:8080/k8s/webssh:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 300Mi
          requests:
            cpu: 30m
            memory: 30Mi
        volumeMounts:
        - name: ssh-log
          mountPath: /code/webssh/static/img
          #readOnly: true
        ports:
        - name: websshport
          containerPort: 8888
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: websshport
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: websshport
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 2
      - name: weblog
        image: nfs.k8s:8080/k8s/nginx:alpine
        imagePullPolicy: Always
        volumeMounts:
        - name: ssh-log
          mountPath: /usr/share/nginx/html
          #readOnly: true
        ports:
        - name: webport
          containerPort: 80
          protocol: TCP

      volumes:
      - name: ssh-log
        emptyDir: {}
      imagePullSecrets:
      - name: harbor-secret
      restartPolicy: Always
  minReadySeconds: 10
  revisionHistoryLimit: 10
    
