apiVersion: v1
kind: Service
metadata:
  name: webssh-svc
  labels:
    app: webssh
spec:
  selector:
      app: webssh
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 31111
  type: NodePort
  selector:
    app: webssh
