apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.prospectors:
      - input_type: log
        paths:
        - /var/log/secure*
        fields:
          type: securelog
        fields_under_root: true
    output.redis:
      hosts: ["172.17.0.91"]
      port: 30379
      password: ""  
      db: 0
      timeout: 5
      key: "securelog"
