kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: nfs.k8s #[已配置的NFS系统的IP地址]
            - name: NFS_PATH
              value: /data #[已配置的NFS系统的挂载路径]
      volumes:
        - name: nfs-client-root
          nfs:
            server: nfs.k8s #[已配置的NFS系统的IP地址]
            path: /data #[已配置的NFS系统的挂载路径]
