apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
