#echo -n C1sco@123 | base64
#=> QzFzY29AMTIz
apiVersion: v1
kind: Secret 
metadata:
  name: mysql-user-pwd
data:
  mysql-root-pwd: QzFzY29AMTIz
  mysql-app-user-pwd: QzFzY29AMTIz
  mysql-test-user-pwd: QzFzY29AMTIz
