apiVersion: v1
kind: Service
metadata:
 name: mysql-svc
 labels:
  app: mysql
  version: "5.7"
spec:
 type: NodePort
 ports:
  - name: mysql-nodeport
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30006
 selector:
  app: mysql
