apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-dbbackup
  labels:
    pv: nfs-pv-dbbackup
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  #storageClassName: nfs
  nfs:
    server: nfs.k8s
    path: "/data/k8s/nfs-pv-dbbackup"
