apiVersion: v1
kind: Service
metadata:
  name: nextcloud-svc
  labels:
    app: nextcloud
spec:
  selector:
      app: nextcloud
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  type: NodePort
  selector:
    app: nextcloud
