apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
  labels:
    pv: gitlab-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  #storageClassName: nfs
  nfs:
    server: nfs.k8s
    path: "/data/k8s/gitlab"
