apiVersion: v1
kind: Service
metadata:
 name: nginx-svc
 labels:
  app: nginx
  version: "alpine"
spec:
 type: NodePort
 ports:
  - name: nginx-nodeport
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30380
 selector:
  app: nginx
  version: "alpine"

