apiVersion: apps/v1
kind: DaemonSet 
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      name: filebeat
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: nfs.k8s:8080/k8s/filebeat:6.8.0
        args: [
          "-c", "/home/filebeat-config/filebeat.yml",
          "-e",
        ]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: filebeat-storage
          mountPath: /var/log
        - name: "filebeat-volume"
          mountPath: "/home/filebeat-config"
      volumes:
      - name: filebeat-storage
        hostPath:
          path: /var/log
      - name: filebeat-volume
        configMap:
          name: filebeat-config
