apiVersion: v1
kind: Service
metadata:
  name: svc-redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  podManagementPolicy: Parallel
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: nfs.k8s:8080/k8s/redis:5.0
        args:  [
          "/var/redis.conf",
        ]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: "redis-conf"
          mountPath: "/var/redis.conf"
      volumes:
      - name: redis-conf
        configMap:
          name: elk-redis-config
---
apiVersion: v1
kind: Service
metadata:
 name: redis-svc
 labels:
  app: redis
  version: "5.0"
spec:
 type: NodePort
 ports:
  - name: redis-nodeport
    port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 30379
 selector:
  app: redis
