apiVersion: v1
kind: Service
metadata:
  name: ipam-svc
  labels:
    app: ipam
    version: "1.4"
spec:
  type: NodePort
  ports:
    - name: ipam-nodeport
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30180
  selector:
    app: ipam
