apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv1
spec:
  capacity:
    storage: 500M      #磁盘大小500M
  accessModes:
    - ReadWriteMany    #多客户可读写
  nfs:
    server: 172.17.250.253
    path: "/data/k8s/redis/pv1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv2
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.17.250.253
    path: "/data/k8s/redis/pv2"

